name: 'Use Pulumi ESC Values'
description: 'Use Pulumi ESC Values in GitHub Actions'
author: 'jaxxstorm'

# Define your inputs here.
inputs:
  access-token:
    description: 'The Pulumi access token to use'
    required: true
  organization:
    description: 'The org name to retrieve environments from'
    required: true
  environment:
    description: 'The Pulumi ESC environment to open'
    required: true
  json-path:
    description: 'A JSON path expression to determine the ESC keys to return from the values'
    required: false
  secret:
    description: 'Whether the returned values should be secret'
    default: 'true'

outputs:
  result:
    description: 'The result of the Pulumi ESC call'

branding:
  icon: "archive"
  color: "green"

runs:
  using: node20
  main: dist/index.js
